### ISSUE TITLE
Include libjpeg_turbo and libpng in the SDK

### ISSUE THREAD

**Issue by DoubangoTelecom** [DoubangoTelecom/FaceLivenessDetection-SDK#26]

**Comment by Vladimir-v1** [comment]
Hello

Our company is still waiting for a solution to a problem we discovered through testing (one of our fake faces shows a live face result), after sending this photo for your review we have been waiting since July 9 and still do not understand if we can get this fix or not, please reply to us!


Thank you in advance!

**Comment by DoubangoTelecom** [comment]
Hi, 
A ticket could take a day, a month or a year to fix. The fact that it's open since July (a month ago) is normal. If you're a license owner, you have access to commercial support and you can directly contact the support team to have the issue fixed. Unfortunately I have no ETA to provide on this ticket.

**Comment by DoubangoTelecom** [comment]
Fixed by v1.3.0
The API has changed, we added a new function: https://www.doubango.org/SDKs/face-liveness/docs/cpp-api.html#_CPPv4N12FaceLiveness12FldSdkEngine7processEPKvK6size_t
This function is used in the Python code which means you'll need to rebuild the extension if you're using Python: https://github.com/DoubangoTelecom/FaceLivenessDetection-SDK/blob/master/python/README.md
Regardless the language (C++, Java, C#, Python...) you'll have to update your code to use the new function.
Before reporting any issue based on you application, make sure the same issue happens using one of the samples (C++, Java, C#, Python...)
